registry:
  image: registry:2
  ports:
    - 80:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - /job/docker-hub:/data
registry-web:
  restart: always
  image: hyper/docker-registry-web
  ports:
    - 8081:8080
  links:
    - registry:registry
  environment:
    REGISTRY_HOST: registry
    REGISTRY_PORT: 5000
nginx:
  image: "nginx:1.9"
  ports:
    - 443:443
  links:
    - registry:registry
  volumes:
    - ./auth/:/etc/nginx/conf.d
